workflows:
  flutter-workflow:
    name: Flutter Workflow with SCA
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Dependencies
        script: |
          pip install Flask

      - name: Start Mock Service
        script: |
          python mock_service.py &
          sleep 5 # Dê tempo para o Flask inicializar completamente
          curl -X GET http://127.0.0.1:5000/ || echo "Flask service did not start"

      - name: Check if service is running
        script: |
          curl -X GET http://127.0.0.1:5000/ || echo "Service not running"

      - name: Run Tests
        script: |
          curl -X POST http://127.0.0.1:5000/base/veracode/
          curl -X POST http://127.0.0.1:5000/base/browserstack/
          curl -X GET http://127.0.0.1:5000/base/cyberark/chave
