workflows:
  flutter-workflow:
    name: Flutter Workflow with SCA
    environment:
      flutter: stable
      xcode: latest
      vars:
        RESPONSE_CYBERARK: "TESTE"
    scripts:
      - name: Instalando dependencias
        script: |
          pip install Flask jq

      - name: Start Mock Service
        script: |
          python mock_service.py &
          sleep 5 # Dê tempo para o Flask inicializar completamente
          curl -X GET http://127.0.0.1:5000/ || echo "Flask service did not start"

      - name: Verificando se o serviço está online
        script: |
          curl -X GET http://127.0.0.1:5000/ || echo "Service not running"

      - name: Obter valor do Cyberark
        script: |
          # Captura o json de resposta e extrai o valor do campo "message" 
          RESPONSE=$(curl -s -X POST http://127.0.0.1:5000/base/veracode/ | jq -r '.message')

          # setando como variavel de ambiente no arquivo de env
          echo "RESPONSE_CYBERARK=$RESPONSE" >> $CM_ENV_PATH

          # output opicional para depurar
          echo "Captured response: $RESPONSE"
        
      - name: Usando os dados recuperados do Cyberark
        script: |
          echo "Resposta capturada do Cyberark: $RESPONSE_CYBERARK"

      - name: Testando endpoints
        script: |
          curl -X POST http://127.0.0.1:5000/base/veracode/
          curl -X POST http://127.0.0.1:5000/base/browserstack/
          curl -X GET http://127.0.0.1:5000/base/cyberark/chave


      - name: Upload para Veracode
        script: |
          # Instalação do Veracode CLI se necessário
          if ! command -v veracode &> /dev/null; then
            brew install veracode
          fi

          # Upload do APK para Veracode
          veracode -action upload -file build/app/outputs/flutter-apk/app-release.apk -appname "SeuAppAndroid" -username ${VERACODE_API_ID} -password ${VERACODE_API_KEY}

          # Upload do IPA para Veracode
          veracode -action upload -file build/ios/ipa/Release-iphoneos/app-release.ipa -appname "SeuAppiOS" -username ${VERACODE_API_ID} -password ${VERACODE_API_KEY}


  #publishing:
  #  webhooks:
  #    - url: http://127.0.0.1:5000/base/webhook/
  #      method: POST
  #      body: |
  #        {
  #          "status": "${status}",
  #          "build_id": "${build_id}",
  #          "workflow": "${workflow_id}"
  #        }
