workflows:
  flutter-workflow:
    name: Flutter Workflow with SCA
    environment:
      flutter: stable
      xcode: latest # se for necessário para builds iOS, ajuste conforme sua necessidade
    scripts:
      - name: Install Dependencies
        script: 
          pip install Flask

      - name: Start Mock Service
        script: 
          python mock_service.py &
      
      - name: Run Tests
        script: 
          curl -X POST http://127.0.0.1:5000/base/veracode/
          curl -X POST http://127.0.0.1:5000/base/browserstack/
          curl -X GET http://127.0.0.1:5000/base/cyberark/chave
